apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets/echovote-secrets.yaml
  - secrets/ghcr-pull-secret.yaml
  - secrets/mongo-secrets.yaml
  - secrets/redis-secrets.yaml
  - infrastructure/mongodb.yaml
  - infrastructure/redis.yaml
  - server/deployment.yaml
  - server/service.yaml
  - client/deployment.yaml
  - client/service.yaml
  - client/ingress.yaml
  - image-automation/imagepolicies.yaml
  - image-automation/imageupdateautomation.yaml
