apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infisical-operator.yaml
  - infisical-auth.yaml
  # Enable after you create Infisical Kubernetes Auth / Machine Identity:
  # - app-secrets.yaml
