---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: orbit-api
  namespace: flux-system
spec:
  image: ghcr.io/chenarrr/orbit-api
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: orbit-web
  namespace: flux-system
spec:
  image: ghcr.io/chenarrr/orbit-web
  interval: 5m
