apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policies.yaml
  - serviceaccounts.yaml
  - secrets/echovote-secrets.yaml
  - secrets/ghcr-pull-secret.yaml
  - secrets/mongo-secrets.yaml
  - secrets/redis-secrets.yaml
  - infrastructure/mongodb.yaml
  - infrastructure/redis-sentinel.yaml
  - redis-v2/redis-sentinel-crd.yaml
  - redis-v2/network-policies.yaml
  - server/deployment.yaml
  - server/service.yaml
  - server/ingress.yaml
  - client/deployment.yaml
  - client/service.yaml
  - client/ingress.yaml
  - image-automation/imagerepositories.yaml
  - image-automation/imagepolicies.yaml
  - image-automation/imageupdateautomation.yaml
  - image-automation/flux-secrets.yaml
