---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echovote-server
  namespace: echovote
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echovote-client
  namespace: echovote
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: echovote
automountServiceAccountToken: false
