apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: orbit-secrets-sync
  namespace: orbit-dev
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    kubernetesAuth:
      identityId: "bb4c4eec-3767-4447-a806-c079360125d0"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: default
      secretsScope:
        projectSlug: "homelab-e-bm-i"
        envSlug: "dev"
        secretsPath: "/orbit"
        recursive: false
  managedKubeSecretReferences:
    - secretName: orbit-secrets
      secretNamespace: orbit-dev
      creationPolicy: Owner
      template:
        includeAllSecrets: true
