apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policies.yaml
  - secrets/orbit-secrets.yaml
  - infrastructure/postgres.yaml
  - api/deployment.yaml
  - api/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
  - image-automation/imagerepositories.yaml
  - image-automation/imagepolicies.yaml
  - image-automation/imageupdateautomation.yaml
