apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ghcr-pull-secret-sync
  namespace: echovote
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    kubernetesAuth:
      identityId: "YOUR_MACHINE_IDENTITY_ID"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: default
      secretsScope:
        projectSlug: "YOUR_PROJECT_SLUG"
        envSlug: "prod"
        secretsPath: "/echovote"
        recursive: false
  managedKubeSecretReferences:
    - secretName: ghcr-pull-secret
      secretNamespace: echovote
      # Key in Infisical must be named: .dockerconfigjson
      secretType: "kubernetes.io/dockerconfigjson"
      creationPolicy: Owner
      template:
        includeAllSecrets: true
