apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policies.yaml
  - serviceaccounts.yaml
  - secrets/postgres-secrets.yaml
  - secrets/liftlog-secrets.yaml
  - secrets/ghcr-pull-secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/ingress-tcp.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - server/deployment.yaml
  - server/service.yaml
  - server/ingress.yaml
  - image-automation/flux-ghcr-secret.yaml
  - image-automation/imagerepositories.yaml
  - image-automation/imagepolicies.yaml
  - image-automation/imageupdateautomation.yaml
