apiVersion: v1
kind: Namespace
metadata:
  name: liftlog
  labels:
    kubernetes.io/metadata.name: liftlog
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
