apiVersion: v1
kind: ServiceAccount
metadata:
  name: liftlog-server
  namespace: liftlog
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: liftlog-postgres
  namespace: liftlog
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: liftlog-redis
  namespace: liftlog
automountServiceAccountToken: false
