apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infisical
  namespace: infisical
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`infisical.chenar.space`)
      kind: Rule
      services:
        - name: infisical-infisical-standalone-infisical
          port: 8080
  tls:
    certResolver: letsencrypt-prod
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: infisical
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infisical-http-redirect
  namespace: infisical
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`infisical.chenar.space`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: infisical-infisical-standalone-infisical
          port: 8080
