apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - secrets/ghcr-pull-secret.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - ui/deployment.yaml
  - ui/service.yaml
  - ui/ingress.yaml
  - image-automation/imagerepositories.yaml
  - image-automation/imagepolicies.yaml
  - image-automation/imageupdateautomation.yaml
