---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-jobs-api
  namespace: ai-jobs
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-jobs-ui
  namespace: ai-jobs
automountServiceAccountToken: false
